on:
  push:
    tags:
      - 'v*'

name: Upload to HumHub Marketplace

jobs:
  build:
    uses: humhub/actions/.github/workflows/module-marketplace-upload.yml@main
    secrets:
      MARKETPLACE_API_KEY: ${{ secrets.MARKETPLACE_API_KEY }}